### ISSUE TITLE
Improve test used to determine if user can connect to plex server to reduce CPU usage

### ISSUE THREAD

**Issue by phobiac** [JourneyDocker/Plex-Auto-Languages#11]
**Describe the bug**
This is an old issue and I originally reported it [https://github.com/RemiRigal/Plex-Auto-Languages/issues/67#issuecomment-1449538724](here) but I'm copying that information over.

The theory from that error report was that the [currently used connection test](https://github.com/JourneyDocker/Plex-Auto-Languages/blob/0a3c50a59c9cb4b597f591dacb9a8017d72649e7/plex_auto_languages/plex_server.py#L35) which calls `plex.library.sections()` for each user is CPU intensive. It may actually be as simple as the retry logic being too aggressive? Regardless my testing showed that it's this check which is being repeated that was spiking CPU usage on my end.

**To Reproduce**
I'm not sure how exactly to reproduce it, but I have this issue come up frequently enough with my users that I can at least test potential fixes...

**Expected behavior**
A more graceful failure if the connection fails that doesn't spike CPU usage.

**Actual Behavior**
Repeated attempts to perform the test that cause high CPU usage.

Environment Details
- **Plex Auto Languages Version:** journeyover/plex-auto-languages:main (pulled today to check)
- **Plex Server Version:** 1.41.3.9314 
- **Operating System (if applicable):** Debian Linux
- **Deployment Method (if applicable):** Docker

Logs and Screenshots
- Logs: [Paste here or attach as a file]

**Comment by JourneyOver** [comment]
Will take a look at improving the currently used connection test when I have some free time (hopefully this weekend), I sadly won't be able to do any testing myself on this however as I only have one extra user on my plex and I haven't ran into this issue myself ever so I will be relying on you to test any changes I make covering this issue.

I'll shoot you a ping whenever I get some commits out for testing.

**Comment by JourneyOver** [comment]
Hey @phobiac 

I just pushed up a commit that will hopefully take care of this by testing the connection with a more lightweight call instead of fetching all sections. Do you mind testing it out for me and seeing if it fixes this issue or not? You'll need to pull with the `:main` tag.

**Comment by Zorro92** [comment]
Is the purpose of this just to ensure we have a valid token for the server?

**Comment by JourneyOver** [comment]
@Zorro92 At least from my understanding the purpose of this is to ensure that the main user and any other users of the server are actually connected or are able to connect to the server.

I tried various things myself locally to see if we could instead just change the timing on how often the check is actually done but everything I tried just ended up in failure as the timing on how often things where checked never seemed to change, so I'm hoping that with the change I did it at least alleviates things at least a bit.

**Comment by JourneyOver** [comment]
Hmm so the above actually runs into a different crashing issue after a tiny bit due to `Failed to get access token for {OTHER_USER}`, so I'm going to revert the code and try some other things out locally and hopefully come up with some kind of solution in the end.

**Comment by JourneyOver** [comment]
I'm thinking I might have something now, I'll need to do a bit more testing locally to at least make sure I don't run into the error I did above (I'm going to test for a couple hours before I deem it worthy of committing), but if I don't run into the error any then I'll push the code up for further testing from you.


If you want to get to testing right away before I actually push the commit up though the change was just changing:
```py
    def __init__(self, url: str, token: str, session: requests.Session = requests.Session()):
        self._session = session
        self._plex_url = url
        self._plex = self._get_server(url, token, self._session)

    @property
    def connected(self):
        if self._plex is None:
            return False
        try:
            _ = self._plex.library.sections()
            return True
        except (BadRequest, RequestsConnectionError):
            return False
```
to:
```py
    def __init__(self, url: str, token: str, session: requests.Session = requests.Session()):
        self._session = session
        self._plex_url = url
        self._plex = self._get_server(url, token, self._session)
        self._last_connection_check = None
        self._connection_check_interval = timedelta(minutes=5)  # Cache connection status for 5 minutes

    @property
    def connected(self):
        if self._plex is None:
            logger.debug("No Plex instance available (self._plex is None)")
            return False
        if self._last_connection_check is not None:
            elapsed_time = datetime.now() - self._last_connection_check
            logger.debug(f"Time since last connection check: {elapsed_time}")
            if elapsed_time < self._connection_check_interval:
                remaining_time = self._connection_check_interval - elapsed_time
                logger.debug(f"Using cached result. Remaining time for next check: {remaining_time}")
                return self._plex is not None
        try:
            logger.debug("Attempting to fetch library sections from Plex")
            sections = self._plex.library.sections()
            if sections:
                logger.debug(f"Sections retrieved: {len(sections)} found. Verifying first section.")
                _ = sections[0]
                self._last_connection_check = datetime.now()
                logger.debug("Connection verified successfully")
                return True
            logger.debug("No sections found in the Plex library")
            return False
        except (BadRequest, RequestsConnectionError, IndexError) as e:
            logger.debug(f"Connection check failed with known exception: {type(e).__name__}: {str(e)}")
            self._last_connection_check = datetime.now()
            return False
        except Exception as e:
            logger.warning(f"Unexpected error during connection check: {type(e).__name__}: {str(e)}")
            self._last_connection_check = datetime.now()
            return False
```

It has debug logging in the code as well as the actual changes, as I wanted to check and see if it was actually going to be using the `_connection_check_interval` and the cached result any and at least from what I can tell it does. 

May not be the best way to do things, but it's just something quick for now until a better solution in the future can be thought of.

**Comment by JourneyOver** [comment]
Alright several hours later of testing and so far I at least haven't ran into any errors myself with the new code so I've gone ahead and pushed it on up. Feel free to run some testing once they are pushed to ghcr and dockerhub @phobiac to see if it solves this issue or not.

**Comment by JourneyOver** [comment]
Welp this setting `trigger_on_activity` being enabled is def going to be the biggest cause of why you are having high CPU usage as it is noted in the config.example.yaml:
```
  # Whether or not navigating the Plex library should trigger a language update, defaults to 'false'
  # Only the Plex web client and the Plex for Windows app support this feature
  # Set this to 'true' only if you want to perform changes whenever the default track of an episode is updated, even when the episode is not played.
  # Setting this parameter to 'true' can result in higher resource usage.
  trigger_on_activity: false
```

It's got me wondering if I should just make a special case for when that setting is set to true or something..

**Comment by phobiac** [comment]
I was going for testing the worst case scenario, and can confirm there's still high CPU usage with this setting. Let me turn trigger on activity off (that's how I typically run) and try it again.

**Comment by JourneyOver** [comment]
From what I understand, having the setting turned off, even with the old method, shouldn't be causing excessively high CPU usage unless you have an egregious number of users that access your plex. I wish I knew where the timer controlling the `connected` check is located so I could adjust it. Unfortunately, every method I've tried to increase the interval between checks has failed, and I haven't been able to find where in the code this is actually managed.

**Comment by Lansenou** [comment]
Hello! My CPU usage gets high after using PAL for a while (4-24 hours).

I can see in my plex console that `/library/sections` is being called a lot of times and quickly. A restart of the container fixes it. I'll try to grab a screenshot when it happens again.

I see that you reverted this change https://github.com/JourneyDocker/Plex-Auto-Languages/commit/709cc7648efbea58786af1217d25cd92a789c945

Could you perhaps make a docker tag with which I could run this version to see if this fixes it?

**Comment by JourneyOver** [comment]
Hello @Lansenou, the reason I reverted that commit, which implemented caching for the library section, is that during my own testing, it didn’t work as expected at all. Every few seconds, it would repeatedly call the cached library info, leading me to believe it would still run into the same problems. Even though I set the `_connection_check_interval` to 5 minutes, it seemed to completely ignore that interval. On top of that, I encountered other issues while trying the caching approach.  

I’ve tested a few other things locally (even though I don’t personally experience high CPU usage) to see if I could better control the connection checks or at least modify the timer. However, I suspect the timer is built into PlexAPI and not something I can change, as none of my attempts made any difference in how often the check was called.

Unfortunately, I haven’t found a solution yet, aside from advising users to keep `trigger_on_activity` set to `false` for now, as that seems to be one of the main culprits of high CPU usage.

**Comment by JourneyOver** [comment]
@Lansenou Could you by chance test the latest commit out? you can pull it with the tag of `:main`

**Comment by Lansenou** [comment]
I happened to catch the console spam again. I think I pointed you in the wrong direction with the  `/library/sections`

 😅.
This is the Plex log when PAL causes the CPU usage to be high.

![Image](https://github.com/user-attachments/assets/651e21e6-8d3e-464d-86ae-a2e3c89873cf)

The 172.25.0.2 is the PAL container.

The `/library/metadata/{id}` call seems to trigger something on the system. And is happening every 50-100 ms. 

This is parhaps the only interesting part in the PAL log.

```
2025-03-17 21:46:00,067 [INFO] Starting alert listener
2025-03-17 21:46:00,068 [INFO] Initialization completed successfully
2025-03-18 03:46:43,452 [INFO] [Timeline] Processing newly added episode 'redacted' (S02E16)
2025-03-18 03:46:46,076 [INFO] Language update: Episode: redacted (S02E16) | Status: New episode | Updated for all users
```

I'm not sure if the newly episode caused the issue or if it's unrelated.

**Comment by Lansenou** [comment]
I will test the :main tag to see if that fixes anything.

**Comment by Lansenou** [comment]
> I happened to catch the console spam again. I think I pointed you in the wrong direction with the `/library/sections`
> 
> 😅. This is the Plex log when PAL causes the CPU usage to be high.
> 
> ![Image](https://github.com/user-attachments/assets/651e21e6-8d3e-464d-86ae-a2e3c89873cf)
> 
> The 172.25.0.2 is the PAL container.
> 
> The `/library/metadata/{id}` call seems to trigger something on the system. And is happening every 50-100 ms.
> 
> This is parhaps the only interesting part in the PAL log.
> 
> ```
> 2025-03-17 21:46:00,067 [INFO] Starting alert listener
> 2025-03-17 21:46:00,068 [INFO] Initialization completed successfully
> 2025-03-18 03:46:43,452 [INFO] [Timeline] Processing newly added episode 'redacted' (S02E16)
> 2025-03-18 03:46:46,076 [INFO] Language update: Episode: redacted (S02E16) | Status: New episode | Updated for all users
> ```
> 
> I'm not sure if the newly episode caused the issue or if it's unrelated.

If I inspect the metadata item that it's requesting something about it's from my pictures library. I've deleted it, and will check if that fixes something.

**Comment by JourneyOver** [comment]
What does your configuration file look like for PAL? (Redact the URL/token for Plex, of course.)

From looking at your console log in Plex, it seems like something is constantly triggering `media analysis` on some items.

-----------------------

I’m not entirely sure how or why PAL would be grabbing any data from a `picture` library, as PAL is specifically set up to only retrieve data from libraries marked as `TV Shows` library type. This is evident in the [`get_show_sections` method](https://github.com/JourneyDocker/Plex-Auto-Languages/blob/main/plex_auto_languages/plex_server.py#L152), which filters the library sections to include only those that are instances of [`ShowSection`](https://github.com/pkkid/python-plexapi/blob/a8d051f29bbadca28dc9bd4bf50f1fb76d0fb77a/plexapi/library.py#L1869).

Depending on whether you are running the `:main` tag or the `:latest` tag, the only time the code interacts with all libraries really is during the [`connected`](https://github.com/JourneyDocker/Plex-Auto-Languages/blob/main/plex_auto_languages/plex_server.py#L63) check. Depending on the tag you’re using, it either calls out every time it runs the `connected` check or it can utilize the new `cached library` system to reduce the number of calls to the libraries.

However, even then, the `connected` check only fetches the library sections to verify that the connection between PAL and Plex is working. It never actually pulls any extra data from the libraries.

**Comment by Lansenou** [comment]
My config looks like this.

```yaml
plexautolanguages:
  # Update language for the entire show or only for the current season
  # Accepted values:
  #   - show (default)
  #   - season
  update_level: "show"

  # Update all episodes of the show/season or only the next ones
  # Accepted values:
  #   - all
  #   - next (default)
  update_strategy: "next"

  # Whether or not playing a file should trigger a language update, defaults to 'true'
  trigger_on_play: true

  # Whether or not scanning the library for new files should trigger a language update, defaults to 'true'
  # A newly added episode will be updated based on the most recently watched episode, or the first episode of the show if it has never been watched
  trigger_on_scan: true

  # Whether or not navigating the Plex library should trigger a language update, defaults to 'false'
  # Only the Plex web client and the Plex for Windows app support this feature
  # Set this to 'true' only if you want to perform changes whenever the default track of an episode is updated, even when the episode is not played.
  # Setting this parameter to 'true' can result in higher resource usage.
  trigger_on_activity: false

  # Whether or not to refresh the cached library whenever the Plex server scans its own library, defaults to 'true'
  # Disabling this parameter will prevent PlexAutoLanguages from detecting updated files for an already existing episode
  # It is recommended to disable this parameter if you have a large TV Show library (10k+ episodes)
  refresh_library_on_scan: false

  # PlexAutoLanguages will ignore shows with any of the following Plex labels
  ignore_labels:
    - PAL_IGNORE

  # # Plex configuration
  # plex:
  #   # A valid Plex URL (required)
  #   url: ""
  #   # A valid Plex Token (required)
  #   token: ""

  scheduler:
    # Whether of not to enable the scheduler, defaults to 'true'
    # The scheduler will perform a deeper analysis of all recently played TV Shows
    enable: false
    # The time at which the scheduler start its task with the format 'HH:MM', defaults to '02:00'
    schedule_time: "02:00"

  notifications:
    # Whether or not to enable the notifications through Apprise, defaults to 'false'
    # A notification is sent whenever a language change is performed
    enable: false
    # An array of Apprise configurations, see Apprise docs for more information: https://github.com/caronc/apprise
    # The array 'users' can be specified in order to link notification URLs with specific users
    #   Defaults to all users if not present
    # The array 'events' can be specified in order to get notifications only for specific events
    #   Valid event values: "play_or_activity" "new_episode" "updated_episode" "scheduler"
    #   Defaults to all events if not present
    apprise_configs:
      # This URL will be notified of all changes during all events
      - "discord://webhook_id/webhook_token"
      # These URLs will only be notified of language change for users "MyUser1" and "MyUser2"
      - urls:
          - "gotify://hostname/token"
          - "pover://user@token"
        users:
          - "MyUser1"
          - "MyUser2"
      # This URL will only be notified of language change for user "MyUser3" during play or activity events
      - urls:
          - "tgram://bottoken/ChatID"
        users:
          - "MyUser3"
        events:
          - "play_or_activity"
      # This URL will be notified of language change during scheduler tasks only
      - urls:
          - "gotify://hostname/token"
        events:
          - "scheduler"
      - "..."

  # Path where the system and cache files are written, defaults to a standard OS specific path if left empty (recommended)
  data_path: ""

  # Whether or not to enable the debug mode, defaults to 'false'
  # Enabling debug mode will significantly increase the number of output logs
  debug: false
```
Plex token comes from the environment. My docker-compose.yaml looks like:
```yaml
services:
  plexautolanguages:
    # image: remirigal/plex-auto-languages:latest
    image: journeyover/plex-auto-languages:latest
    volumes:
      - ./config:/config
    environment:
      - TZ=Europe/Amsterdam
```

I've been running it on the old :latest image for 10 hours after deleting the images library, with the cpu usage still being fine. I also know for sure that it's PAL seeing as how my cpu levels & messages always dropped to normal, after restarting PAL.
